In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r"tmdbdf.csv")

In [3]:
df = df.head(4000)

In [4]:
df

,Unnamed: 0,index,id,title,overview,keywords,genres,poster_path
0,0,0,27205,Inception,"Cobb, a skilled thief who commits corporate es...","rescue,mission,dream,airplane,paris,france,vir...","Action,ScienceFiction,Adventure",/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg
1,1,1,157336,Interstellar,The adventures of a group of explorers who mak...,"rescue,future,spacecraft,raceagainsttime,artif...","Adventure,Drama,ScienceFiction",/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg
2,2,2,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,"joker,sadism,chaos,secretidentity,crimefighter...","Drama,Action,Crime,Thriller",/qJ2tW6WMUDux911r6m7haRef0WH.jpg
3,3,3,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","future,society,cultureclash,spacetravel,spacew...","Action,Adventure,Fantasy,ScienceFiction",/kyeqWdyUXW608qlYkRqosgbbJyK.jpg
4,4,4,24428,The Avengers,When an unexpected enemy emerges and threatens...,"newyorkcity,superhero,shield,basedoncomic,alie...","ScienceFiction,Action,Adventure",/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg
...,...,...,...,...,...,...,...,...
3995,3995,3995,77495,Sleep Tight,"César, an unhappy concierge, maintains a pecul...","jealousy,barcelona,spain,blackmail,manipulatio...","Thriller,Horror",/i44Mr6t3reXt7z28OMCPZTllRfr.jpg
3996,3996,3996,316154,The Bad Batch,Arlen is sent to a fenced-off wasteland where ...,"amputation,kidnapping,dystopia,post-apocalypti...","Drama,Horror,ScienceFiction",/7o14VaMphEIzPwzeW6FP3A6zb4W.jpg
3997,3997,3997,711,Finding Forrester,Gus Van Sant tells the story of a young Africa...,"dyinganddeath,highschool,friendship,scholarshi...",Drama,/heHi6n68fDiQoUc7SMletM9Adjz.jpg
3998,3998,3998,10760,Sydney White,A modern retelling of Snow White set against s...,"plumber,college,geek,romance,hazing,sorority,s...",Comedy,/ce3NNmhVZY5NkUe5Y8Je8CciKqf.jpg
3999,3999,3999,74018,A Cinderella Story: Once Upon a Song,"In this modern telling of the classic tale, as...","highschool,aspiringsinger,orphan,teenageromanc...","Comedy,Family,Romance",/awuuwPA8Hy9c5EH04xwkEXOSYiL.jpg

In [5]:
df.isnull().sum()

Unnamed: 0      0
index           0
id              0
title           0
overview        0
keywords       42
genres          0
poster_path     0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.describe()

        Unnamed: 0        index            id
count  4000.000000  4000.000000  4.000000e+03
mean   1999.500000  1999.500000  1.615251e+05
std    1154.844867  1154.844867  2.248007e+05
min       0.000000     0.000000  5.000000e+00
25%     999.750000   999.750000  7.296250e+03
50%    1999.500000  1999.500000  2.521600e+04
75%    2999.250000  2999.250000  2.959970e+05
max    3999.000000  3999.000000  1.102776e+06

In [8]:
df.describe(include=object)

C:\Users\B VIJAYA LAKSHMI\AppData\Local\Temp\ipykernel_16848\3998025828.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include=object)

,title,overview,keywords,genres,poster_path
count,4000,4000,3958,4000,4000
unique,3922,4000,3945,1197,4000
top,Beauty and the Beast,"Cobb, a skilled thief who commits corporate es...",duringcreditsstinger,Drama,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg
freq,3,1,4,183,1

In [9]:
df["tags"]=df["overview"].fillna(" ")+df["keywords"].fillna(" ")+df["genres"].fillna(" ")

In [10]:
df["tags"].isna().sum()

np.int64(0)

In [11]:
df["tags"]

0       Cobb, a skilled thief who commits corporate es...
1       The adventures of a group of explorers who mak...
2       Batman raises the stakes in his war on crime. ...
3       In the 22nd century, a paraplegic Marine is di...
4       When an unexpected enemy emerges and threatens...
                              ...
3995    César, an unhappy concierge, maintains a pecul...
3996    Arlen is sent to a fenced-off wasteland where ...
3997    Gus Van Sant tells the story of a young Africa...
3998    A modern retelling of Snow White set against s...
3999    In this modern telling of the classic tale, as...
Name: tags, Length: 4000, dtype: str

### Lower Case

In [12]:
df["tags"] = df["tags"].apply(lambda x:x.lower())

In [13]:
df["tags"]

0       cobb, a skilled thief who commits corporate es...
1       the adventures of a group of explorers who mak...
2       batman raises the stakes in his war on crime. ...
3       in the 22nd century, a paraplegic marine is di...
4       when an unexpected enemy emerges and threatens...
                              ...
3995    césar, an unhappy concierge, maintains a pecul...
3996    arlen is sent to a fenced-off wasteland where ...
3997    gus van sant tells the story of a young africa...
3998    a modern retelling of snow white set against s...
3999    in this modern telling of the classic tale, as...
Name: tags, Length: 4000, dtype: str

### Removing Tags and Punctuation

df['tags'] = df['tags'].str.replace(r'[^\w\s]',"",regex=True)
df['tags']

### Stemming

In [16]:
from nltk.stem import PorterStemmer

In [17]:
ps = PorterStemmer()

In [18]:
ps.stem("running")

'run'

In [19]:
def stemming(word):
    y=[]
    for i in word.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [20]:
df["tags"]

0       cobb, a skilled thief who commits corporate es...
1       the adventures of a group of explorers who mak...
2       batman raises the stakes in his war on crime. ...
3       in the 22nd century, a paraplegic marine is di...
4       when an unexpected enemy emerges and threatens...
                              ...
3995    césar, an unhappy concierge, maintains a pecul...
3996    arlen is sent to a fenced-off wasteland where ...
3997    gus van sant tells the story of a young africa...
3998    a modern retelling of snow white set against s...
3999    in this modern telling of the classic tale, as...
Name: tags, Length: 4000, dtype: str

In [21]:
df["tags"]=df["tags"].apply(stemming)
df["tags"]

0       cobb, a skill thief who commit corpor espionag...
1       the adventur of a group of explor who make use...
2       batman rais the stake in hi war on crime. with...
3       in the 22nd century, a parapleg marin is dispa...
4       when an unexpect enemi emerg and threaten glob...
                              ...
3995    césar, an unhappi concierge, maintain a peculi...
3996    arlen is sent to a fenced-off wasteland where ...
3997    gu van sant tell the stori of a young african ...
3998    a modern retel of snow white set against stude...
3999    in thi modern tell of the classic tale, aspir ...
Name: tags, Length: 4000, dtype: str

### Converting into Vectors

In [22]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [23]:
tf = TfidfVectorizer(max_features=21000, stop_words="english")

In [24]:
vector = tf.fit_transform(df["tags"])

In [25]:
tf.get_feature_names_out().tolist()

['00',
 '000',
 '007',
 '10',
 '100',
 '1000',
 '101',
 '1021',
 '108',
 '10thcentury',
 '10thcenturyadventure',
 '11',
 '114',
 '117',
 '118th',
 '11crime',
 '11drama',
 '11th',
 '11thcentury',
 '12',
 '120',
 '1200',
 '12th',
 '12thcentury',
 '13',
 '14',
 '1453',
 '14th',
 '14thcentury',
 '15',
 '150',
 '15th',
 '15thcentury',
 '16',
 '16th',
 '16thcentury',
 '17',
 '17th',
 '17thcentury',
 '17thcenturydrama',
 '18',
 '1800s',
 '1862',
 '1863',
 '1870s',
 '1879',
 '1890',
 '1890s',
 '1892',
 '18th',
 '18thcentury',
 '19',
 '1900',
 '1900s',
 '1910',
 '1910s',
 '1917',
 '1920',
 '1920s',
 '1920sdrama',
 '1925',
 '1927',
 '1930',
 '1930s',
 '1930sadventure',
 '1930scomedy',
 '1930scrime',
 '1930sdrama',
 '1935',
 '1936',
 '1937',
 '1938',
 '1939',
 '1940',
 '1940s',
 '1940saction',
 '1940scomedy',
 '1940sdrama',
 '1940swar',
 '1941',
 '1942',
 '1944',
 '1945',
 '1947',
 '1949',
 '1950',
 '1950s',
 '1950saction',
 '1950scrime',
 '1950sdrama',
 '1952',
 '1955',
 '1956',
 '1957',
 '1958',
 '1960',
 '1960s',
 '1960saction',
 '1960scomedy',
 '1960scrime',
 '1960sdrama',
 '1962',
 '1963',
 '1964',
 '1965',
 '1967',
 '1968',
 '1969',
 '1970',
 '1970s',
 '1972',
 '1973',
 '1977',
 '1978',
 '1979',
 '1980',
 '1980s',
 '1980saction',
 '1980scomedy',
 '1980sdrama',
 '1981',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1990',
 '1990s',
 '1990shorror',
 '1991',
 '1992',
 '1994',
 '1995',
 '1996',
 '1999',
 '19comedi',
 '19th',
 '19thcentury',
 '19thcenturyadventure',
 '19thcenturyanimation',
 '19thcenturydrama',
 '19thcenturywestern',
 '1stcentury',
 '1stcenturyfamily',
 '20',
 '200',
 '2000s',
 '2000ssciencefiction',
 '2001',
 '2009',
 '2010',
 '2010s',
 '2011',
 '2013',
 '2015',
 '2016',
 '2019',
 '2028',
 '2029',
 '2030s',
 '2030saction',
 '2035',
 '2040s',
 '2040saction',
 '2070saction',
 '20s',
 '20th',
 '21',
 '21st',
 '22',
 '22nd',
 '22ndcentury',
 '23',
 '23rd',
 '23rdcentury',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '2ndcentury',
 '30',
 '300',
 '31',
 '35',
 '39',
 '3danimation',
 '3po',
 '40',
 '400',
 '45',
 '47',
 '476',
 '50',
 '500',
 '51',
 '5thcenturybc',
 '60',
 '600',
 '60s',
 '70',
 '70s',
 '72',
 '80',
 '800',
 '80sthrowback',
 '86',
 '90s',
 '911',
 '95',
 'aaron',
 'abandon',
 'abandoned',
 'abandonedhouse',
 'abandonedmine',
 'abba',
 'abbey',
 'abbi',
 'abby',
 'abduct',
 'abducted',
 'abduction',
 'abe',
 'abigail',
 'abil',
 'abilities',
 'abl',
 'aboard',
 'abod',
 'abolitionist',
 'abortion',
 'abov',
 'abra',
 'abraham',
 'abrahamlincoln',
 'abroad',
 'abrupt',
 'absenc',
 'absent',
 'absolut',
 'absorb',
 'absurd',
 'absurdcomedy',
 'absurdism',
 'abus',
 'abuse',
 'abusedwoman',
 'abuseofpower',
 'abusivefamily',
 'abusivehusband',
 'abusivemother',
 'aca',
 'academ',
 'academi',
 'academia',
 'academy',
 'acapella',
 'accents',
 'accept',
 'acceptance',
 'access',
 'accid',
 'accident',
 'accidentaldeath',
 'accidentdrama',
 'acclaim',
 'accommod',
 'accompani',
 'accomplic',
 'accomplish',
 'accord',
 'account',
 'accountant',
 'accus',
 'accusedofmurder',
 'ace',
 'ach',
 'achiev',
 'acid',
 'acknowledg',
 'acm',
 'acquaint',
 'acquir',
 'acquit',
 'act',
 'action',
 'actionhero',
 'actionheroaction',
 'actionheroadventure',
 'actionherothriller',
 'actions',
 'activ',
 'activist',
 'activities',
 'activity',
 'actor',
 'actorplayingthemselfcomedy',
 'actors',
 'actress',
 'actual',
 'acupuncture',
 'ad',
 'ada',
 'adalin',
 'adam',
 'adams',
 'adapt',
 'adaptation',
 'add',
 'addam',
 'addict',
 'addicted',
 'addiction',
 'addit',
 'addl',
 'adel',
 'adelaid',
 'adjust',
 'administr',
 'admir',
 'admired',
 'admiring',
 'admit',
 'admonit',
 'adolesc',
 'adolescence',
 'adolf',
 'adolfhitler',
 'adolfhitlerdrama',
 'adoni',
 'adopt',
 'adoptedson',
 'adoption',
 'adoptivefather',
 'ador',
 'adoring',
 'adrenalin',
 'adrenaline',
 'adrenalinejunkie',
 'adrian',
 'adrift',
 'adult',
 'adultanimation',
 'adultasachild',
 'adultery',
 'adulthood',
 'adults',
 'advanc',
 'advantag',
 'advantage',
 'adventur',
 'adventure',
 'adventurer',
 'adventures',
 'adversari',
 'adversaries',
 'adversary',
 'advertis',
 'advertising',
 'advertisingexecutive',
 'advertisingexpert',
 'advic',
 'advice',
 'advicecolumnist',
 'advis',
 'advisor',
 'advoc',
 'aerial',
 'affair',
 'affect',
 'affection',
 'afflict',
 'afford',
 'afghan',
 'afghanistan',
 'afghanistanwar',
 'afoul',
 'afraid',
 'africa',
 'african',
 'africanamericanhistory',
 'africanamericanhistorydrama',
 'aftercreditsstinger',
 'aftercreditsstingeraction',
 'aftercreditsstingeradventure',
 'aftercreditsstingercomedi',
 'aftercreditsstingercrime',
 'aftercreditsstingerfamily',
 'afterlife',
 'aftermath',
 'afternoon',
 'ag',
 'againsttheodds',
 'agamemnon',
 'agatha',
 'age',
 'agedifference',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agentadventure',
 'agents',
 'aggie',
 'aggress',
 'aggression',
 'aggressive',
 'aggressors',
 'aging',
 'agingactor',
 'ago',
 'agoraphobia',
 'agre',
 'agrees',
 'agu',
 'ahead',
 'ahsoka',
 'aid',
 'aids',
 'ail',
 'aim',
 'aime',
 'aimless',
 'air',
 'airborn',
 'aircraft',
 'aircraftcarrier',
 'airforce',
 'airforceone',
 'airlin',
 'airpirate',
 'airplan',
 'airplane',
 'airplaneaccident',
 'airplanecrash',
 'airplanehijacking',
 'airport',
 'airportlounge',
 'airship',
 'aisle',
 'aka',
 'akelarre',
 'aki',
 'al',
 'alabama',
 'aladdin',
 'alan',
 'alarm',
 'alarmclock',
 'alaska',
 'alaskan',
 'albanian',
 'albeit',
 'albert',
 'alberto',
 'albino',
 'album',
 'alcatraz',
 'alcatrazprison',
 'alcohol',
 'alcoholabuse',
 'alcoholic',
 'alcoholism',
 'aldo',
 'aldou',
 'alec',
 'alejandro',
 'alert',
 'alex',
 'alexand',
 'alexander',
 'alexanderthegreat',
 'alexia',
 'alfr',
 'algorithm',
 'algren',
 'ali',
 'alias',
 'alibi',
 'alic',
 'alice',
 'alicia',
 'alien',
 'alienabduction',
 'alienation',
 'alienattack',
 'aliencontact',
 'aliencreature',
 'alienencounter',
 'alienfriendship',
 'alieninfection',
 'alieninvasion',
 'alieninvasionsciencefiction',
 'alienlanguage',
 'alienlife',
 'alienmonster',
 'alienparasites',
 'alienplanet',
 'alienrace',
 'aliens',
 'alienspacecraft',
 'alientechnology',
 'alik',
 'alike',
 'alisdair',
 'aliv',
 'alive',
 'allan',
 'allegedli',
 'allegory',
 'allegra',
 'allen',
 'allerg',
 'allergy',
 'alley',
 'alli',
 'allianc',
 'allies',
 'alligator',
 'allow',
 'allur',
 'ally',
 'alma',
 'almightyfantasy',
 'almási',
 'alon',
 'alongsid',
 'alp',
 'alpha',
 'alps',
 'alpsmountains',
 'alqaeda',
 'alreadi',
 'alt',
 'altar',
 'alter',
 'alterego',
 'altern',
 'alternatedimension',
 'alternatehistory',
 'alternatereality',
 'alternatetimeline',
 'alternateuniverseaction',
 'alternative',
 'alternativeuniverse',
 'alternativeworld',
 'alvin',
 'alway',
 'alzheimer',
 'amanda',
 'amateur',
 'amateurdetective',
 'amaz',
 'amazing',
 'amazon',
 'amazonrainforest',
 'ambassador',
 'ambiguity',
 'ambiguoushorror',
 'ambit',
 'ambiti',
 'ambition',
 'ambul',
 'ambulance',
 'ambush',
 'amelia',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americancountrysidehorror',
 'americandream',
 'americanfootball',
 'americanfootballcoach',
 'americanhistorydrama',
 'americans',
 'americanspycomedy',
 'americanwest',
 'americanwilderness',
 'ami',
 'amiabl',
 'amid',
 'amidst',
 'amish',
 'amiti',
 'amnesia',
 'amnesiac',
 'amok',
 'amor',
 'amputation',
 'amsterdam',
 'amulet',
 'amus',
 'amused',
 'amusedaction',
 'amusedcomedy',
 'amusementpark',
 'amy',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedy',
 'anarchiccomedycomedi',
 'anarchist',
 'anastasia',
 'ancestor',
 'ancestry',
 'anchor',
 'anchorman',
 'ancient',
 'ancientcivilization',
 'ancientegypt',
 'ancientevil',
 'ancientgreece',
 'ancientrome',
 'ancientwarfare',
 'ancientworld',
 'anderson',
 'anderton',
 'andesmountains',
 'andi',
 'andrew',
 'androgyny',
 'android',
 'andy',
 'angel',
 'angela',
 'angeles',
 'angelov',
 'angels',
 'anger',
 'angermanagement',
 'angri',
 'angry',
 'angrymob',
 'angst',
 'ani',
 'anim',
 'animal',
 'animalattack',
 'animalcruelty',
 'animalhorror',
 'animalhorroraction',
 'animalkilling',
 'animallead',
 'animalmask',
 'animals',
 'animalsidekick',
 'animalsidekickadventure',
 'animated',
 'animatedscene',
 'animation',
 'anime',
 'animeaction',
 'animeadventure',
 'animeanimation',
 'animefantasy',
 'anita',
 'ann',
 'anna',
 'annabel',
 'annabelle',
 'anne',
 'anni',
 'annie',
 'annihil',
 'annihilation',
 'annika',
 'anniversari',
 'announc',
 'annoy',
 'annual',
 'anonym',
 'anonymity',
 'anonymousletter',
 'anorexia',
 'anoth',
 'anotherdimension',
 'anselmi',
 'answer',
 'answers',
 'ant',
 'antagonistic',
 'antagonistichorror',
 'antarctica',
 'anthology',
 'anthoni',
 'anthropology',
 'anthropomorphicanimalsciencefiction',
 'anthropomorphism',
 'anti',
 'antic',
 'anticip',
 'antics',
 'antidote',
 'antihero',
 'antiqu',
 'antisocialpersonalitydisorder',
 'antiwar',
 'antoin',
 'anton',
 'antonio',
 'anubis',
 'anxieti',
 'anxiety',
 'anxiou',
 'anxious',
 'anybodi',
 'anymore',
 'anyon',
 'anyth',
 'anywher',
 'aokigahara',
 'apart',
 'apartheid',
 'apartment',
 'apartmentbuilding',
 'ape',
 'apes',
 'apocalypse',
 'apocalypt',
 'apocalypticfuture',
 'apollo',
 'app',
 'appalachia',
 'appalachian',
 'appar',
 'apparit',
 'apparition',
 'appeal',
 'appear',
 'appears',
 'appetit',
 'appl',
 'apple',
 'appletree',
 'appli',
 'appoint',
 'appreci',
 'appreciative',
 'apprehend',
 'apprentic',
 'apprentice',
 'approach',
 'approaches',
 'approaching',
 'april',
 'aquarium',
 'ar',
 'arab',
 'arabia',
 'arabian',
 'arabiannights',
 'aragorn',
 'arbitrarylaw',
 'arcade',
 'arcadegame',
 'arch',
 'archaeologist',
 'archdiocese',
 'archenemi',
 'archeology',
 'archer',
 'archery',
 'archibald',
 'architect',
 'architecture',
 'arctic',
 'arcticpolarcircleregion',
 'arduou',
 'area',
 'area51',
 'aren',
 'arena',
 'argentina',
 'argument',
 'ariel',
 'aris',
 'arises',
 'aristocracy',
 'aristocrat',
 'arizona',
 'ark',
 'arkansa',
 'arkansas',
 'arkofthecovenant',
 'arm',
 'armada',
 'armageddon',
 'armand',
 'armi',
 'armor',
 'armoredcar',
 'arms',
 'armsdeal',
 'armsdealer',
 'armssmuggling',
 'armstrong',
 'army',
 'armyveteran',
 'arnie',
 'aroundtheworld',
 'arrang',
 'arrangedmarriage',
 'array',
 'arren',
 'arrest',
 'arrested',
 'arriv',
 'arrival',
 'arrives',
 'arriving',
 'arrog',
 'arrogance',
 'arrogant',
 'arrow',
 'arson',
 'art',
 'artagnan',
 'artcollector',
 'artdealer',
 'artemi',
 'artgallery',
 'arthistory',
 'arthouse',
 'arthur',
 'articl',
 'artifact',
 'artifici',
 'artificialinsemination',
 'artificialintelligence',
 'artist',
 'artists',
 'arts',
 'artschool',
 'arttheft',
 'artthief',
 'artwork',
 'asami',
 'ascend',
 'ascens',
 'asgard',
 'asger',
 'ash',
 'ashitaka',
 'ashley',
 'ashore',
 'ashtray',
 'asia',
 'asianamerican',
 'asianamericancomedy',
 'asianorigins',
 'asid',
 'ask',
 'asleep',
 'aspect',
 'aspen',
 'asperger',
 'aspir',
 'aspiration',
 'aspiringactor',
 'aspiringsinger',
 'aspiringwriter',
 'ass',
 'assail',
 'assassin',
 'assassination',
 'assassinationattempt',
 'assassinationplot',
 'assassinationteam',
 'assassins',
 'assault',
 'assaultrifle',
 'assembl',
 'assert',
 'asset',
 'assign',
 'assignment',
 'assimil',
 'assist',
 'assistant',
 'associ',
 'associate',
 'assort',
 'assum',
 'assumedidentity',
 'assur',
 'asterix',
 'asteroid',
 'astonish',
 'astro',
 'astronaut',
 'astronom',
 'astronomer',
 'astrophysicist',
 'asylum',
 'atenton',
 'atheist',
 'athlet',
 'atlanta',
 'atlanti',
 'atlanticcity',
 'atlanticocean',
 'atlantis',
 'atmospher',
 'atom',
 'atomicbomb',
 'atrocity',
 'attach',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attemptedmurder',
 'attemptedrape',
 'attempttoescape',
 'attend',
 'attent',
 'attention',
 'attic',
 'attica',
 'attitud',
 'attitude',
 'attorney',
 'attract',
 'attraction',
 'attractive',
 'aubrey',
 'auction',
 'auctioneer',
 'audac',
 'audaci',
 'audaciouscrime',
 'audienc',
 'audience',
 'audiorecording',
 'audiotape',
 'audit',
 'audition',
 'audrey',
 'august',
 'aunt',
 'auntnephewrelationship',
 'aurora',
 'austen',
 'austin',
 'australia',
 'australian',
 'australianoutback',
 'austria',
 'austrian',
 'author',
 'authoritarian',
 'authorities',
 'authority',
 'autism',
 'auto',
 'autobiography',
 'autobot',
 'autograph',
 'automaton',
 'automobil',
 'automobile',
 'autonomy',
 'autopsy',
 'autumn',
 'avail',
 'avalanche',
 'avant',
 'avantgarde',
 'avatars',
 'aveng',
 'avenger',
 'avengers',
 'avenu',
 'averag',
 'averi',
 'avert',
 'aviat',
 'aviation',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awakening',
 'awar',
 'award',
 'away',
 'awe',
 'awesom',
 'awestruck',
 'awkward',
 'awol',
 'awri',
 'awry',
 'ax',
 'axdrama',
 'axe',
 ...]

### Calcuating the Similarity

In [26]:
from sklearn.metrics.pairwise import cosine_similarity

In [27]:
similarity = cosine_similarity(vector)

In [28]:
similaritydf = pd.DataFrame(similarity, index=df["title"], columns=df["title"])
similaritydf

title,Inception,Interstellar,The Dark Knight,Avatar,The Avengers,Deadpool,Avengers: Infinity War,Fight Club,Guardians of the Galaxy,Pulp Fiction,...,Barnyard,Stigmata,The Broken Circle Breakdown,Like Crazy,Gosford Park,Sleep Tight,The Bad Batch,Finding Forrester,Sydney White,A Cinderella Story: Once Upon a Song
title,,,,,,,,,,,,,,,,,,,,,
Inception,1.000000,0.043572,0.003485,0.011558,0.021833,0.014759,0.007198,0.000000,0.070193,0.032563,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.022623,0.019247,0.017467,0.000000,0.019738
Interstellar,0.043572,1.000000,0.000000,0.066970,0.008742,0.000000,0.038321,0.016561,0.077045,0.014866,...,0.053212,0.000000,0.000000,0.000000,0.009457,0.019897,0.034701,0.005492,0.026083,0.000000
The Dark Knight,0.003485,0.000000,1.000000,0.000000,0.042481,0.043222,0.034924,0.000000,0.019594,0.025392,...,0.000000,0.025533,0.000000,0.000000,0.004157,0.000000,0.000000,0.010021,0.008255,0.002133
Avatar,0.011558,0.066970,0.000000,1.000000,0.000000,0.007495,0.032490,0.000000,0.020973,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.007184,0.000000,0.011890,0.000000,0.012545,0.000000
The Avengers,0.021833,0.008742,0.042481,0.000000,1.000000,0.040188,0.108463,0.000000,0.156729,0.009460,...,0.000000,0.000000,0.033674,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sleep Tight,0.022623,0.019897,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.020654,0.000000,0.000000,0.000000,1.000000,0.011486,0.000000,0.000000,0.000000
The Bad Batch,0.019247,0.034701,0.000000,0.011890,0.000000,0.000000,0.009762,0.013511,0.000000,0.000000,...,0.018195,0.000000,0.000000,0.000000,0.013980,0.011486,1.000000,0.000000,0.000000,0.000000
Finding Forrester,0.017467,0.005492,0.010021,0.000000,0.000000,0.030959,0.012834,0.008625,0.008444,0.018372,...,0.012228,0.016032,0.010604,0.015108,0.000000,0.000000,0.000000,1.000000,0.000000,0.053505
Sydney White,0.000000,0.026083,0.008255,0.012545,0.000000,0.000000,0.000000,0.000000,0.019997,0.000000,...,0.000000,0.000000,0.000000,0.084006,0.000000,0.000000,0.000000,0.000000,1.000000,0.028401
A Cinderella Story: Once Upon a Song,0.019738,0.000000,0.002133,0.000000,0.000000,0.012869,0.019278,0.017986,0.028016,0.012463,...,0.050153,0.010448,0.000000,0.035863,0.000000,0.000000,0.000000,0.053505,0.028401,1.000000

In [29]:
similaritydf["Inception"].sort_values(ascending=False)[1:6]

title
Upgrade                            0.100670
The Matrix                         0.100203
The Matrix Revolutions             0.098457
Charlie's Angels: Full Throttle    0.094003
Kiss Kiss Bang Bang                0.091888
Name: Inception, dtype: float64

In [30]:
similaritydf["Avatar"].sort_values(ascending=False)[1:6]

title
Predators              0.142798
Aliens                 0.135091
Battle: Los Angeles    0.134959
Meet Dave              0.130653
First Man              0.125778
Name: Avatar, dtype: float64

In [31]:
df.loc[df["title"]=="Avatar"].index[0]

3

In [32]:
def recommend(movie):
    idx = df[df["title"]==movie].index[0]  # returns index of movie
    movie_list = np.argsort(similaritydf.iloc[idx])[::-1][1:6]
    return df.iloc[movie_list].title.tolist()

In [33]:
recommend("Avatar")

['Predators', 'Aliens', 'Battle: Los Angeles', 'Meet Dave', 'First Man']

In [34]:
df["poster_path"]

0       /oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg
1       /gEU2QniE6E77NI6lCU6MxlNBvIx.jpg
2       /qJ2tW6WMUDux911r6m7haRef0WH.jpg
3       /kyeqWdyUXW608qlYkRqosgbbJyK.jpg
4        /RYMX2wcKCBAr24UyPD7xwmjaTn.jpg
                      ...
3995    /i44Mr6t3reXt7z28OMCPZTllRfr.jpg
3996    /7o14VaMphEIzPwzeW6FP3A6zb4W.jpg
3997    /heHi6n68fDiQoUc7SMletM9Adjz.jpg
3998    /ce3NNmhVZY5NkUe5Y8Je8CciKqf.jpg
3999    /awuuwPA8Hy9c5EH04xwkEXOSYiL.jpg
Name: poster_path, Length: 4000, dtype: str

In [35]:
print('/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg')

/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg

In [36]:
baseurl = 'https://image.tmdb.org/t/p/w500'
print(baseurl+'/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg')

https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg

In [37]:
import pickle 
with open(r"D:\ML\ML Phase 2\Un Supervised ML\Recommendation.pkl", 'wb')as f: 
    pickle.dump(similaritydf, f)